
<nav aria-label="breadcrumb" class="bg-light p-3 rounded">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="./statistiques.php"><i class="bi bi-house-door-fill"></i></a></li>
            <li class="breadcrumb-item"><a href="./index.php">Livres</a></li>
            <li class="breadcrumb-item active" aria-current="page">Details</li>
        </ol>
</nav>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4 text-center">
                <img src="./assets/images/profile.png" alt="Profile Picture" class="img-fluid rounded-circle mb-3">
                <h2 class="text-primary">Livre Details</h2>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center mb-4">Livre Information</h3>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Titre</h5>
                            <p class="card-text"><?= $lvr['titre'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Auteur</h5>
                            <p class="card-text"><?= $lvr['auteur'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Disponibilté</h5>
                            <p class="card-text"><?= $lvr['disponibilite']?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Genre</h5>
                            <p class="card-text"><?=$lvr['genre']?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Resumé</h5>
                            <p class="card-text"><?= $lvr['resume'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Date d'ajout</h5>
                            <p class="card-text"><?= $lvr['date_ajout'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Date de modification</h5>
                            <p class="card-text"><?= $lvr['date_modification'] ?></p>
                        </div>
                        <div class="d-flex justify-content-center mt-4">
                            <a class="btn btn-success mx-2" href="./modifier_livre.php?id=<?= $_GET['id'] ?>" role="button">Modifier</a>
                            <a class="btn btn-danger mx-2" href="./supprimer_livre.php?id=<?= $_GET['id'] ?>" role="button">Supprimer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>