<table class="table table-striped">
    <thead>
        <tr>
                    <th>ID</th>
                    <th>Nom Membre </th>
                    <th>Titre</th>
                    <th>Date d'emprunt</th>
                    <th>Date de retour</th>
                    <th>Status</th>
        </tr>
    </thead>
    <tbody>
                <?php foreach ($historys as $history): ?>
                    <tr>
                        <td><?= $history['id'] ?></td>
                        <td><?= $history['nom'] ?></td>
                        <td><?= $history['titre'] ?></td>
                        <td><?= $history['date_emprunt'] ?></td>
                        <td><?= $history['date_retour'] ?></td>
                        <td>
                            <span class="badge <?= $history['statut'] == 'En cours' ? 'bg-success' : ($history['statut'] == 'Retard' ? 'bg-danger' : 'bg-secondary') ?>">
                                <?= $history['statut']?>
                            </span>
                    </tr>
                <?php endforeach; ?>
            </tbody>

    </table>