    <div class="d-flex justify-content-between align-items-center my-5">
        <h1>Liste des utilisateurs</h1>
        <h1><a href="./ajout_utilisateur.php"><i class="bi bi-plus"></i></a></h1>
    </div>
    <?php if (isset($_SESSION['success'])): ?>
        <div id="message" class="alert alert-success" role="alert">
            Member ajouté avec succée !
        </div>
        <?php unset($_SESSION['success']) ?>
    <?php endif ?>

    <?php if (isset($_SESSION['danger'])): ?>
        <div id="message" class="alert alert-danger" role="alert">
            Member supprimé avec succée !
        </div>
        <?php unset($_SESSION['danger']) ?>
    <?php endif ?>
    <?php if (isset($_SESSION['error'])): ?>
        <div id="message" class="alert alert-danger" role="alert">
            Membre Existe Deja!
        </div>
        <?php unset($_SESSION['error']) ?>
    <?php endif ?>
    <?php if (isset($_SESSION['update-success'])): ?>
        <div id="message" class="alert alert-success" role="alert">
            Membre modifié avec succées!
        </div>
        <?php unset($_SESSION['update-success']) ?>
    <?php endif ?>


    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Full Name</th>
                <th scope="col">Email</th>
                <th scope="col">Telephone</th>
                <th scope="col">Operations</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($utils as $util): ?>
            <tr>
                <th scope="row"><?= $util['id'] ?></th>
                <td><?= $util['full_name'] ?></td>
                <td><?= $util['email'] ?></td>
                <td><?= $util['telephone'] ?></td>
                <td>
                    <a class="btn btn-primary" href="utilisateur_details.php?id=<?= $util['id'] ?>" role="button"><i class="bi bi-info-circle-fill"></i></a>
                    <a class="btn btn-success" href="modifier_utilisateur.php?id=<?= $util['id'] ?>" role="button"><i class="bi bi-pencil"></i></a>
                    <a class="btn btn-danger" role="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop<?=$util['id']?>"><i class="bi bi-trash"></i></a>
                    <div class="modal fade" id="staticBackdrop<?=$util['id']?>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel<?=$util['id']?>" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="staticBackdropLabel<?=$util['id']?>">Supprimer adhérent <?=$util['full_name']?></h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Êtes-vous sûr de vouloir supprimer cet adhérent ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                    
                                    <a class="btn btn-primary" href="supprimer_utilisateur.php?id=<?=$util['id']?>" role="button">Yes</a>
                                
                                </div>
                        </div>
                        </div>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
