<?php
$current_page = basename($_SERVER['PHP_SELF']); // Récupère le nom de la page actuelle
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="./assets/css/style.css">
    <title><?= $page_title ?></title>
</head>
<body>
    <?php if($template == 'login'): ?>
        <div class="login-container">
            <?php header("location: login.php") ?>
        </div>
    <?php else: ?>
        <div class="sidebar">
            <div class="logo"></div>
            <ul class="menu">
                <li class="<?= $current_page == 'statistiques.php' ? 'active' : '' ?>">
                    <a href="./statistiques.php">
                        <i class="bi bi-speedometer"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="<?= $current_page == 'index.php' ? 'active' : '' ?>">
                    <a href="./index.php">
                        <i class="bi bi-people-fill"></i>
                        <span>Utilisateur</span>
                    </a>
                </li>
                <li class="<?= $current_page == 'liste_livres.php' ? 'active' : '' ?>">
                    <a href="./liste_livres.php">
                        <i class="bi bi-book"></i>
                        <span>Livres</span>
                    </a>
                </li>
                <li class="<?= $current_page == 'liste_emprunts.php' ? 'active' : '' ?>">
                    <a href="./liste_emprunts.php">
                        <i class="bi bi-arrow-left-right"></i>
                        <span>Emprunts</span>
                    </a>
                </li>
                <li class="<?= $current_page == 'liste_admins.php' ? 'active' : '' ?>">
                    <a href="./liste_admins.php">
                        <i class="fa-solid fa-user-tie"></i>
                        <span>Admins</span>
                    </a>
                </li>
                <li>
                    <a href="logout.php">
                        <i class="bi bi-box-arrow-right"></i>
                        <span>Déconnexion</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="main--content">
            <div class="header--wrapper">
                <div class="header--title">
                    <span>Bibliotheque</span>
                    <h2>Dashboard</h2>
                </div>
                <div class="user--info">
                    <span><?= $_SESSION["full_name"] ?></span>
                    <a href="./profile.php"><img src="assets/images/profile.png"></a>
                </div>
            </div>
            <div class="tabular--wrapper">
                <?php include $template . '.phtml'; ?>
            </div>
        </div>
    <?php endif; ?>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="./assets/js/script.js"></script>
</body>
</html>
