<div class="d-flex justify-content-between align-items-center my-5">
        <h1>Liste des admins</h1>
        <h1><a href="./ajout_admin.php"><i class="bi bi-plus"></i></a></h1>
    </div>
    <?php if (isset($_SESSION['add-success'])): ?>
        <div id="message" class="alert alert-success" role="alert">
            Admin added successfully!
        </div>
        <?php unset($_SESSION['add-success']) ?>
    <?php endif ?>
    <?php if (isset($_SESSION['danger'])): ?>
        <div id="message" class="alert alert-danger" role="alert">
            Admin deleted successfully!
        </div>
        <?php unset($_SESSION['danger']) ?>
    <?php endif ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Full Name</th>
                <th scope="col">Email</th>
                <th scope="col">Telephone</th>
                <th scope="col">Operations</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($utils as $util): ?>
            <tr>
                <th scope="row"><?= $util['id'] ?></th>
                <td><?= $util['full_name'] ?></td>
                <td><?= $util['email'] ?></td>
                <td><?= $util['telephone'] ?></td>
                <td>
                    <a class="btn btn-primary" href="utilisateur_details.php?id=<?= $util['id'] ?>" role="button"><i class="bi bi-info-circle-fill"></i></a>
                    <!--<a class="btn btn-success" href="modifier_admin.php?id=<?= $util['id'] ?>" role="button"><i class="bi bi-pencil"></i></a>-->
                    <a class="btn btn-danger" role="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop<?=$util['id']?>"><i class="bi bi-trash"></i></a>
                    <div class="modal fade" id="staticBackdrop<?=$util['id']?>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel<?=$util['id']?>" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="staticBackdropLabel<?=$util['id']?>">Supprimer admin <?=$util['full_name']?></h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Êtes-vous sûr de vouloir supprimer cet admin ?
                                </div>
                                <div class="modal-footer">
                                    <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuller</a>
                                    <a class="btn btn-danger" href="supprimer_admin.php?id=<?=$util['id']?>" role="button">Supprimer</a>
                                </div>
                        </div>
                        </div>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
