<nav aria-label="breadcrumb" class="bg-light p-3 rounded">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="./statistiques.php"><i class="bi bi-house-door-fill"></i></a></li>
            <li class="breadcrumb-item"><a href="./index.php">Livres</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modifier Livre</li>
        </ol>
    </nav>
    <div class="d-flex justify-content-start align-items-center mb-4">
        <h1><a href="./liste_livres.php" class="text-decoration-none"><i class="bi bi-arrow-left-circle"></i></a></h1>
        <h1 class="mx-3">Modifier Livre</h1>
    </div>

    <div class="form-container">
        <form method="post" action="./modifier_livre.php?id=<?= $book['id']?>">
            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <label for="titre" class="form-label">Titre</label>
                    <input type="text" class="form-control" value="<?= $book['titre']?>" id="titre" name="titre" required>
                </div>
                <div class="col-md-6">
                    <label for="auteur" class="form-label">Auteur</label>
                    <input type="text" class="form-control" value="<?= $book['auteur']?>" id="auteur" name="auteur" required>
                </div>
            </div>
            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <label for="genre" class="form-label">Genre</label>
                    <select class="form-select" name="genre" id="genre">
                        <option value="Classique" <?= $book['genre'] == 'Classique' ? 'selected' : '' ?>>Classique</option>
                        <option value="Roman" <?= $book['genre'] == 'Roman' ? 'selected' : '' ?>>Roman</option>
                        <option value="Science-fiction" <?= $book['genre'] == 'Science-fiction' ? 'selected' : '' ?> >Science-fiction</option>
                        <option value="Thriller/Policier" <?= $book['genre'] == 'Thriller/Policier' ? 'selected' : '' ?> >Thriller/Policier</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="dispo" class="form-label">Nombre Copies</label>
                    <input type="number" value="<?= $book['disponibilite']?>" class="form-control" id="dispo" name="dispo" required>
                </div>
            </div>
            <div class="row g-3 mb-3">
                <div class="col-md-12">
                    <label for="resume" class="form-label">Resumé</label>
                    <textarea class="form-control"  name="resume" id="resume" cols="30" rows="5"><?= $book['resume']?></textarea>
                </div>
            </div>
            <div class="col-12">
                <button class="btn btn-success" type="submit">Modifier</button>
                <a href="./liste_livres.php" class="btn btn-secondary">Annuler</a>
            </div>
        </form>
    </div>