<nav aria-label="breadcrumb" class="bg-light p-3 rounded">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="./index.php"><i class="bi bi-house-door-fill"></i></a></li>
            <li class="breadcrumb-item"><a href="./index.php">Profile</a></li>
            <li class="breadcrumb-item active" aria-current="page">Details</li>
        </ol>
    </nav>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4 text-center">
                <img src="./assets/images/profile.png" alt="Profile Picture" class="img-fluid rounded-circle mb-3">
                <h2 class="text-primary">Profile Details</h2>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center mb-4">User Information</h3>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Full Name</h5>
                            <p class="card-text"><?= $utils['full_name'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Email</h5>
                            <p class="card-text"><?= $utils['email'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Telephone</h5>
                            <p class="card-text"><?= $utils['telephone'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Role</h5>
                            <p class="card-text"><?=$utils['Role']?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Date d'inscription</h5>
                            <p class="card-text"><?= $utils['date_inscription'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Date de modification</h5>
                            <p class="card-text"><?= $utils['date_modification'] ?></p>
                        </div>
                        <div class="mb-3">
                            <h5 class="card-subtitle">Date de naissance</h5>
                            <p class="card-text"><?= $utils['date_naissance'] ?></p>
                        </div>
                        <div class="d-flex justify-content-center mt-4">
                            <a class="btn btn-success  mx-2" href="modifier_admin.php?id=<?= $_SESSION['id'] ?>" role="button">Modifier</a>
                            <a class="btn btn-danger mx-2" href="supprimer_admin.php?id=<?= $_SESSION['id'] ?>" role="button">Supprimer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>