<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sign Up Form</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="./assets/css/logsign.css">
</head>
<body>
  <div class="library-logo-container">
    <img src="./assets/images/logo.jpg" alt="Library Logo">
    <h1 class="library-name">Success Library</h1>
  </div>
  
  <div class="log-sign-container">
    <div class="login-img">
      <img src="./assets/images/container-img.avif" alt="Library Image">
    </div>

    <div class="container text-center">
      <h1>Create New Account</h1>
         <?php
                if(count($errors) > 0) {
                    foreach($errors as $error) {
                    echo "<div class='alert alert-danger'>$error</div>";
                    }
                } 
                
          ?>

      <form action="<?=$_SERVER['PHP_SELF']?>" method="post">
        <div class="form-group">
          <input type="text" class="form-control" name="nom" placeholder="Nom">
          <i class="bi bi-person"></i>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" name="prenom" placeholder="Prenom">
          <i class="bi bi-person"></i>
        </div>
        <div class="form-group">
          <input type="email" class="form-control" name="email" placeholder="Email">
          <i class="bi bi-envelope"></i>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" name="phone" placeholder="Telephone">
          <i class="bi bi-telephone"></i>
        </div>
        <div class="form-group">
          <input type="date" class="form-control" name="date" placeholder="Date de naissance">
          <i class="bi bi-date"></i>
        </div>
        <div class="form-group">
          <input type="password" class="form-control" name="password" placeholder="Mot de passe">
          <i class="bi bi-lock"></i>
        </div>
        <div class="form-group">
          <input type="password" class="form-control" name="repeat_password" placeholder="confirmer le mot de passe">
          <i class="bi bi-lock"></i>
        </div>
        <div class="form-group">
          <input type="submit" name="submit" value="Register" class="btn btn-primary">
        </div>
        <div class="form-group">
          <a href="login.php">Already a member? Login</a>
        </div>
      </form>
    </div>
  </div>
</body>
</html>